#!/usr/bin/env bash
#
# banking 77
# python bert_train.py --do_train --model_name "bert-seed1-banking77.bin" --num_classes 77 --result_filename "bert-test-seed1-banking77" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl"
# python bert_train.py --do_get_dataset --seed 1 --model_name "bert-seed1-bertadam-banking77.bin" --num_classes 77 --result_filename "bert-train-seed1-banking77" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl"
# python bert_train.py --do_test --var 6.43 --seed 1 --model_name "bert-seed1-bertadam-banking77.bin" --num_classes 77 --result_filename "bert-test-seed1-banking77" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl"
# python bert_train.py --do_train --model_name "bert-seed1-bertadam-banking77.bin" --num_classes 77 --result_filename "bert-test-seed1-banking77" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl"
# 
# python bert_train.py --do_get_dataset --seed 1 --model_name "roberta-seed1-bertadam-banking77.bin" --num_classes 77 --result_filename "bert-train-seed1-banking77" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/codespace/model/roberta-base" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl"
# python bert_train.py --do_get_dataset --seed 2 --model_name "roberta-seed1-bertadam-banking77.bin" --num_classes 77 --result_filename "bert-train-seed1-banking77" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/codespace/model/roberta-base" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl"
# python bert_train.py --do_get_dataset --seed 3 --model_name "roberta-seed1-bertadam-banking77.bin" --num_classes 77 --result_filename "bert-train-seed1-banking77" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/codespace/model/roberta-base" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl"
# python bert_train.py --do_get_dataset --seed 4 --model_name "roberta-seed1-bertadam-banking77.bin" --num_classes 77 --result_filename "bert-train-seed1-banking77" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/codespace/model/roberta-base" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl"
# python bert_train.py --do_get_dataset --seed 5 --model_name "roberta-seed1-bertadam-banking77.bin" --num_classes 77 --result_filename "bert-train-seed1-banking77" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/codespace/model/roberta-base" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl"
# 
#
#
#
#cmcc-train
# roberta
# python bert_train.py --do_train --seed 1 --model_name "roberta-cmcc-seed1-origin-bertadam.bin" --result_filename "result-seed1-origin-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_train --seed 2 --model_name "roberta-cmcc-seed2-origin-bertadam.bin" --result_filename "result-seed2-origin-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_train --seed 3 --model_name "roberta-cmcc-seed3-origin-bertadam.bin" --result_filename "result-seed3-origin-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_train --seed 4 --model_name "roberta-cmcc-seed4-origin-bertadam.bin" --result_filename "result-seed4-origin-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_train --seed 5 --model_name "roberta-cmcc-seed5-origin-bertadam.bin" --result_filename "result-seed5-origin-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# roberta get-var
# python bert_train.py --do_get_dataset --seed 1 --model_name "roberta-cmcc-seed1-origin-bertadam.bin" --result_filename "result-seed1-roberta-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_get_dataset --seed 2 --model_name "roberta-cmcc-seed2-origin-bertadam.bin" --result_filename "result-seed2-roberta-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_get_dataset --seed 3 --model_name "roberta-cmcc-seed3-origin-bertadam.bin" --result_filename "result-seed3-roberta-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_get_dataset --seed 4 --model_name "roberta-cmcc-seed4-origin-bertadam.bin" --result_filename "result-seed4-roberta-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_get_dataset --seed 5 --model_name "roberta-cmcc-seed5-origin-bertadam.bin" --result_filename "result-seed5-roberta-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# roberta test
# python bert_train.py --do_test --var 1.28 --seed 1 --model_name "roberta-cmcc-seed1-origin-bertadam.bin" --result_filename "result-seed1-roberta-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_test --var 1.44 --seed 2 --model_name "roberta-cmcc-seed2-origin-bertadam.bin" --result_filename "result-seed2-roberta-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_test --var 1.3 --seed 3 --model_name "roberta-cmcc-seed3-origin-bertadam.bin" --result_filename "result-seed3-roberta-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_test --var 1.07 --seed 4 --model_name "roberta-cmcc-seed4-origin-bertadam.bin" --result_filename "result-seed4-roberta-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_test --var 1.06 --seed 5 --model_name "roberta-cmcc-seed5-origin-bertadam.bin" --result_filename "result-seed5-roberta-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/codespace/model/chinese_roberta_wwm_ext" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# cmcc-test 
# python bert_train.py --do_test --seed 1 --model_name "bert-cmcc-seed1-origin-bertadam.bin" --result_filename "result-seed1-origin-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_test --seed 2 --model_name "bert-cmcc-seed2-origin-bertadam.bin" --result_filename "result-seed2-origin-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_test --seed 3 --model_name "bert-cmcc-seed3-origin-bertadam.bin" --result_filename "result-seed3-origin-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_test --seed 4 --model_name "bert-cmcc-seed4-origin-bertadam.bin" --result_filename "result-seed4-origin-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_test --seed 5 --model_name "bert-cmcc-seed5-origin-bertadam.bin" --result_filename "result-seed5-origin-test" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# cmcc-get-var
# python bert_train.py --do_get_dataset --seed 1 --model_name "bert-cmcc-seed1-origin-bertadam.bin" --result_filename "result-seed1-origin-dev" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_get_dataset --seed 2 --model_name "bert-cmcc-seed2-origin-bertadam.bin" --result_filename "result-seed2-origin-dev" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_get_dataset --seed 3 --model_name "bert-cmcc-seed3-origin-bertadam.bin" --result_filename "result-seed3-origin-dev" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_get_dataset --seed 4 --model_name "bert-cmcc-seed4-origin-bertadam.bin" --result_filename "result-seed4-origin-dev" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_get_dataset --seed 5 --model_name "bert-cmcc-seed5-origin-bertadam.bin" --result_filename "result-seed5-origin-dev" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
#
# iflytek-train
# python bert_train.py --do_train --seed 1 --model_name "bert-iflytek-seed1-origin-bertadam.bin" --result_filename "result-iflytek-seed1-origin-test" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_train --seed 2 --model_name "bert-iflytek-seed2-origin-bertadam.bin" --result_filename "result-iflytek-seed2-origin-test" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_train --seed 3 --model_name "bert-iflytek-seed3-origin-bertadam.bin" --result_filename "result-iflytek-seed3-origin-test" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_train --seed 4 --model_name "bert-iflytek-seed4-origin-bertadam.bin" --result_filename "result-iflytek-seed4-origin-test" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_train --seed 5 --model_name "bert-iflytek-seed5-origin-bertadam.bin" --result_filename "result-iflytek-seed5-origin-test" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# iflytek-get-var
# python bert_train.py --do_get_dataset --seed 1 --model_name "bert-iflytek-seed1-origin-bertadam.bin" --result_filename "result-iflytek-seed1-origin-dev" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_get_dataset --seed 2 --model_name "bert-iflytek-seed2-origin-bertadam.bin" --result_filename "result-iflytek-seed2-origin-dev" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_get_dataset --seed 3 --model_name "bert-iflytek-seed3-origin-bertadam.bin" --result_filename "result-iflytek-seed3-origin-dev" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_get_dataset --seed 4 --model_name "bert-iflytek-seed4-origin-bertadam.bin" --result_filename "result-iflytek-seed4-origin-dev" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_get_dataset --seed 5 --model_name "bert-iflytek-seed5-origin-bertadam.bin" --result_filename "result-iflytek-seed5-origin-dev" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# iflytek-test
# python bert_train.py --do_test --seed 1 --model_name "bert-iflytek-seed1-origin-bertadam.bin" --result_filename "result-iflytek-seed1-origin-test" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_test --seed 2 --model_name "bert-iflytek-seed2-origin-bertadam.bin" --result_filename "result-iflytek-seed2-origin-test" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_test --seed 3 --model_name "bert-iflytek-seed3-origin-bertadam.bin" --result_filename "result-iflytek-seed3-origin-test" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_test --seed 4 --model_name "bert-iflytek-seed4-origin-bertadam.bin" --result_filename "result-iflytek-seed4-origin-test" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_test --seed 5 --model_name "bert-iflytek-seed5-origin-bertadam.bin" --result_filename "result-iflytek-seed5-origin-test" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
#
#
#
# bert
# cmcc
# python bert_train.py --do_train --seed 1 --model_name "bert-cmcc-seed1.bin" --result_filename "bert-cmcc-seed1" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_train --seed 2 --model_name "bert-cmcc-seed2.bin" --result_filename "bert-cmcc-seed2" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_train --seed 3 --model_name "bert-cmcc-seed3.bin" --result_filename "bert-cmcc-seed3" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_train --seed 4 --model_name "bert-cmcc-seed4.bin" --result_filename "bert-cmcc-seed4" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_train --seed 5 --model_name "bert-cmcc-seed5.bin" --result_filename "bert-cmcc-seed5" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# # iflytek
# python bert_train.py --do_train --seed 1 --model_name "bert-iflytek-seed1.bin" --result_filename "bert-iflytek-seed1" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_train --seed 2 --model_name "bert-iflytek-seed2.bin" --result_filename "bert-iflytek-seed2" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_train --seed 3 --model_name "bert-iflytek-seed3.bin" --result_filename "bert-iflytek-seed3" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_train --seed 4 --model_name "bert-iflytek-seed4.bin" --result_filename "bert-iflytek-seed4" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_train --seed 5 --model_name "bert-iflytek-seed5.bin" --result_filename "bert-iflytek-seed5" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# # banking77
# python bert_train.py --do_train --seed 1 --model_name "bert-banking77-seed1.bin" --num_classes 77 --result_filename "bert-banking77-seed1" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl"
# python bert_train.py --do_train --seed 2 --model_name "bert-banking77-seed2.bin" --num_classes 77 --result_filename "bert-banking77-seed2" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl"
# python bert_train.py --do_train --seed 3 --model_name "bert-banking77-seed3.bin" --num_classes 77 --result_filename "bert-banking77-seed3" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl"
# python bert_train.py --do_train --seed 4 --model_name "bert-banking77-seed4.bin" --num_classes 77 --result_filename "bert-banking77-seed4" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl"
# python bert_train.py --do_train --seed 5 --model_name "bert-banking77-seed5.bin" --num_classes 77 --result_filename "bert-banking77-seed5" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl"
#
# get-finetune-dataset
# python bert_train.py --do_get_dataset --seed 1 --model_name "bert-cmcc-seed1.bin" --result_filename "bert-cmcc-seed1" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# python bert_train.py --do_get_dataset --seed 1 --model_name "bert-iflytek-seed1.bin" --result_filename "bert-iflytek-seed1" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek" --max_seq_len 150
# python bert_train.py --do_get_dataset --seed 1 --model_name "bert-banking77-seed1.bin" --num_classes 77 --result_filename "bert-banking77-seed1" --batch_size 24 --patience 8 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --epochs 48
# # get-valid-var
# # cmcc
# python bert_train.py --do_get_var --seed 1 --model_name "bert-cmcc-seed1.bin" --result_filename "bert-cmcc-seed1" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_get_var --seed 2 --model_name "bert-cmcc-seed2.bin" --result_filename "bert-cmcc-seed2" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_get_var --seed 3 --model_name "bert-cmcc-seed3.bin" --result_filename "bert-cmcc-seed3" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_get_var --seed 4 --model_name "bert-cmcc-seed4.bin" --result_filename "bert-cmcc-seed4" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# python bert_train.py --do_get_var --seed 5 --model_name "bert-cmcc-seed5.bin" --result_filename "bert-cmcc-seed5" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# iflytek
# python bert_train.py --do_get_var --seed 1 --model_name "bert-iflytek-seed1.bin" --result_filename "bert-iflytek-seed1" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_get_var --seed 2 --model_name "bert-iflytek-seed2.bin" --result_filename "bert-iflytek-seed2" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_get_var --seed 3 --model_name "bert-iflytek-seed3.bin" --result_filename "bert-iflytek-seed3" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_get_var --seed 4 --model_name "bert-iflytek-seed4.bin" --result_filename "bert-iflytek-seed4" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# python bert_train.py --do_get_var --seed 5 --model_name "bert-iflytek-seed5.bin" --result_filename "bert-iflytek-seed5" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_formattag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek"
# banking77
# python bert_train.py --do_get_var --seed 1 --model_name "bert-banking77-seed1.bin" --num_classes 77 --result_filename "bert-banking77-seed1" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --max_seq_len 150
# python bert_train.py --do_get_var --seed 2 --model_name "bert-banking77-seed2.bin" --num_classes 77 --result_filename "bert-banking77-seed2" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --max_seq_len 150
# python bert_train.py --do_get_var --seed 3 --model_name "bert-banking77-seed3.bin" --num_classes 77 --result_filename "bert-banking77-seed3" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --max_seq_len 150
# python bert_train.py --do_get_var --seed 4 --model_name "bert-banking77-seed4.bin" --num_classes 77 --result_filename "bert-banking77-seed4" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --max_seq_len 150
# python bert_train.py --do_get_var --seed 5 --model_name "bert-banking77-seed5.bin" --num_classes 77 --result_filename "bert-banking77-seed5" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --max_seq_len 150
#
# rerank-test
# cmcc
# python bert_train.py --do_test --seed 1 --var 10 --model_name "base_model.bin" --result_filename "base-bert-cmcc-seed1" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# per=3.09
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 1 --var 1.34 --model_name "bert-cmcc-seed1.bin" --result_filename "bert-cmcc-seed1" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 2 --var 1.34 --model_name "bert-cmcc-seed2.bin" --result_filename "bert-cmcc-seed2" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# python bert_train.py --do_test --seed 3 --var 1.52 --model_name "bert-cmcc-seed3.bin" --result_filename "bert-cmcc-seed3" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# python bert_train.py --do_test --seed 4 --var 1.21 --model_name "bert-cmcc-seed4.bin" --result_filename "bert-cmcc-seed4" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# python bert_train.py --do_test --seed 5 --var 1.35 --model_name "bert-cmcc-seed5.bin" --result_filename "bert-cmcc-seed5" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# iflytek
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_topk_acc --seed 1 --var 1.85 --model_name "bert-iflytek-seed1.bin" --result_filename "bert-iflytek-seed1-valid" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 1 --var 1.85 --model_name "bert-iflytek-seed1.bin" --result_filename "bert-iflytek-seed1-valid" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 2 --var 1.7 --model_name "bert-iflytek-seed2.bin" --result_filename "bert-iflytek-seed2-valid" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 3 --var 1.56 --model_name "bert-iflytek-seed3.bin" --result_filename "bert-iflytek-seed3-valid" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 4 --var 2.01 --model_name "bert-iflytek-seed4.bin" --result_filename "bert-iflytek-seed4-valid" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 5 --var 1.79 --model_name "bert-iflytek-seed5.bin" --result_filename "bert-iflytek-seed5-test" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-iflytek" --max_seq_len 150
# banking77
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_topk_acc --seed 1 --var 5.14 --model_name "bert-banking77-seed1.bin" --num_classes 77 --result_filename "bert-banking77-seed1" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 1 --var 5.14 --model_name "bert-banking77-seed1.bin" --num_classes 77 --result_filename "bert-banking77-seed1" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 2 --var 4.14 --model_name "bert-banking77-seed2.bin" --num_classes 77 --result_filename "bert-banking77-seed2" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 3 --var 4.71 --model_name "bert-banking77-seed3.bin" --num_classes 77 --result_filename "bert-banking77-seed3" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 4 --var 2.86 --model_name "bert-banking77-seed4.bin" --num_classes 77 --result_filename "bert-banking77-seed4" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 5 --var 4.46 --model_name "bert-banking77-seed5.bin" --num_classes 77 --result_filename "bert-banking77-seed5" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# banking 77 自定义方差
# python bert_train.py --do_test --seed 1 --var 10 --model_name "bert-banking77-seed1.bin" --num_classes 77 --result_filename "bert-banking77-seed1" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# python bert_train.py --do_test --seed 2 --var 10 --model_name "bert-banking77-seed2.bin" --num_classes 77 --result_filename "bert-banking77-seed2" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# python bert_train.py --do_test --seed 3 --var 10 --model_name "bert-banking77-seed3.bin" --num_classes 77 --result_filename "bert-banking77-seed3" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# python bert_train.py --do_test --seed 4 --var 10 --model_name "bert-banking77-seed4.bin" --num_classes 77 --result_filename "bert-banking77-seed4" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# python bert_train.py --do_test --seed 5 --var 10 --model_name "bert-banking77-seed5.bin" --num_classes 77 --result_filename "bert-banking77-seed5" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# rerank-test 消融
# cmcc
# CUDA_VISIBLE_DEVICES=2 python bert_train.py --do_get_dataset --seed 1 --var 1.34 --model_name "bert-cmcc-seed1.bin" --result_filename "bert-cmcc-seed1" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# per=7.25
# CUDA_VISIBLE_DEVICES=2 python bert_train.py --do_test --seed 1 --topk 10 --var 7.25 --model_name "bert-cmcc-seed1.bin" --result_filename "bert-cmcc-seed1" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=2 python bert_train.py --do_test --seed 1 --topk 3 --var 3.09 --model_name "bert-cmcc-seed1.bin" --result_filename "bert-cmcc-seed1" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=2 python bert_train.py --do_test --seed 1 --topk 3 --var 2.5 --model_name "bert-cmcc-seed1.bin" --result_filename "bert-cmcc-seed1" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# 
#
# CUDA_VISIBLE_DEVICES=2 python bert_train.py --do_get_var --seed 1 --var 1.34 --topk 3 --model_name "bert-cmcc-seed1.bin" --result_filename "bert-cmcc-seed1" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=2 python bert_train.py --do_test --seed 1 --var 1.34 --model_name "bert-cmcc-seed1.bin" --result_filename "bert-cmcc-seed1" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/public_model/text_embedding/m3e-base/m3e-base" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=2 python bert_train.py --do_test --seed 1 --var 1.34 --model_name "bert-cmcc-seed1.bin" --result_filename "bert-cmcc-seed1" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=2 python bert_train.py --do_test --seed 2 --var 1.34 --model_name "bert-cmcc-seed2.bin" --result_filename "bert-cmcc-seed2" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=2 python bert_train.py --do_test --seed 3 --var 1.52 --model_name "bert-cmcc-seed3.bin" --result_filename "bert-cmcc-seed3" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=2 python bert_train.py --do_test --seed 4 --var 1.21 --model_name "bert-cmcc-seed4.bin" --result_filename "bert-cmcc-seed4" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=2 python bert_train.py --do_test --seed 5 --var 1.35 --model_name "bert-cmcc-seed5.bin" --result_filename "bert-cmcc-seed5" --batch_size 24 --patience 8 --epochs 48  --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc" --max_seq_len 150
# iflytek
# CUDA_VISIBLE_DEVICES=0 python bert_train.py --do_test --seed 1 --var 1.85 --model_name "bert-iflytek-seed1.bin" --result_filename "bert-iflytek-seed1-test-notriple" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_format/tag_dict.pkl" --embed_model_path "/data/text2vec/bad/roberta-iflytek" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=0 python bert_train.py --do_test --seed 1 --var 1.85 --model_name "bert-iflytek-seed1.bin" --result_filename "bert-iflytek-seed1-test-nofinetune" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-chinese" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=0 python bert_train.py --do_test --seed 1 --var 1.85 --model_name "bert-iflytek-seed1.bin" --result_filename "bert-iflytek-seed1-valid" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_format/tag_dict.pkl" --embed_model_path "/data/text2vec/bad/roberta-iflytek" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 2 --var 1.7 --model_name "bert-iflytek-seed2.bin" --result_filename "bert-iflytek-seed2-valid" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_format/tag_dict.pkl" --embed_model_path "/data/text2vec/bad/roberta-iflytek" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 3 --var 1.56 --model_name "bert-iflytek-seed3.bin" --result_filename "bert-iflytek-seed3-valid" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_format/tag_dict.pkl" --embed_model_path "/data/text2vec/bad/roberta-iflytek" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 4 --var 2.01 --model_name "bert-iflytek-seed4.bin" --result_filename "bert-iflytek-seed4-valid" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_format/tag_dict.pkl" --embed_model_path "/data/text2vec/bad/roberta-iflytek" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_test --seed 5 --var 1.79 --model_name "bert-iflytek-seed5.bin" --result_filename "bert-iflytek-seed5-valid" --num_classes 119 --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/dataset/zh/IFlyTek_format" --tag_path "/data/dataset/zh/IFlyTek_format/tag_dict.pkl" --embed_model_path "/data/text2vec/bad/roberta-iflytek" --max_seq_len 150
# banking77
# CUDA_VISIBLE_DEVICES=0 python bert_train.py --do_test --seed 1 --var 5.14 --model_name "bert-banking77-seed1.bin" --num_classes 77 --result_filename "bert-banking77-seed1" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=0 python bert_train.py --do_test --seed 2 --var 4.14 --model_name "bert-banking77-seed2.bin" --num_classes 77 --result_filename "bert-banking77-seed2" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=0 python bert_train.py --do_test --seed 3 --var 4.71 --model_name "bert-banking77-seed3.bin" --num_classes 77 --result_filename "bert-banking77-seed3" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=0 python bert_train.py --do_test --seed 4 --var 2.86 --model_name "bert-banking77-seed4.bin" --num_classes 77 --result_filename "bert-banking77-seed4" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
# CUDA_VISIBLE_DEVICES=0 python bert_train.py --do_test --seed 5 --var 4.46 --model_name "bert-banking77-seed5.bin" --num_classes 77 --result_filename "bert-banking77-seed5" --batch_size 24 --patience 8 --epochs 48 --bert_path "/data/bert-base-uncased" --data_folder "/data/dataset/en/banking77_format" --tag_path "/data/dataset/en/banking77_format/tag_dict.pkl" --embed_model_path "/data/text2vec/roberta-banking77" --max_seq_len 150
#
# topk acc
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_topk_acc --seed 1 --model_name "bert-cmcc-seed1.bin" --result_filename "bert-cmcc-seed1" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_topk_acc --seed 2 --model_name "bert-cmcc-seed2.bin" --result_filename "bert-cmcc-seed2" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_topk_acc --seed 3 --model_name "bert-cmcc-seed3.bin" --result_filename "bert-cmcc-seed3" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_topk_acc --seed 4 --model_name "bert-cmcc-seed4.bin" --result_filename "bert-cmcc-seed4" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
# CUDA_VISIBLE_DEVICES=1 python bert_train.py --do_topk_acc --seed 5 --model_name "bert-cmcc-seed5.bin" --result_filename "bert-cmcc-seed5" --batch_size 24 --patience 8 --epochs 48 --max_seq_len 150 --bert_path "/data/public_model/pytorch_chinese_L-12_H-768_A-12" --data_folder "/data/gumbou/codespace/dataset/zh/cmcc" --tag_path "/data/gumbou/codespace/dataset/zh/cmcc/tag_dict.pkl" --embed_model_path "/data/gumbou/codespace/work-backup/text2vec/roberta-cmcc"
#
